### ISSUE TITLE
Model parameter mismatch

### ISSUE THREAD

**Issue by XLechter** [Junyi42/sd-dino#16]
Hi, thanks for sharing the codes.

I found a problem when running the demo codes. I followed all the setup in readme without changing anything, but it seems the download pre-trained weights mismatch the model:

![image](https://github.com/Junyi42/sd-dino/assets/41005111/5adfd076-fa00-49b2-b0ae-762b492e05c4)

so I got the results which are very different from yours:
![image](https://github.com/Junyi42/sd-dino/assets/41005111/71c9582e-1015-4d1f-b64a-f0679de82bb7)

This problem also occurs when I run Geoaware-SC. Could you give me some advice on how to solve this?

**Comment by Junyi42** [comment]
Hi, thanks for your interest in our work!

The problem of weights mismatch is as expected, because the features we used for correspondence is different from the one used to generate the segmentation mask in ODISE (more details in [Supp.](https://sd-complements-dino.github.io/sd_dino_files/NIPS_23_Fusing_SD_DINO_cr_supp.pdf) Tab. 2). One simple fix is to set `decoder_only=False` for generating the mask, though the correspondence quality might be slightly lower.

Please refer to #12 and #1 (both are similar or same issue) for more details. Thanks!

**Comment by XLechter** [comment]
@Junyi42 Thank you so much. My issue is well resolved.
