### ISSUE TITLE
Code for PCA

### ISSUE THREAD

**Issue by develop-productivity** [Junyi42/sd-dino#3]
https://github.com/Junyi42/sd-dino/blob/48278d9c3c1cc2386ca08438d527a35dff902c9d/extractor_sd.py#L260C1-L269C100
I guess the dimensions of `tensor` are [N, H*W, C], I don’t know why `transformed_tensor` here only transforms `tensor[0]` and discards other samples, so that new features will only have one sample features, i.e., [1, H*W, C].

**Comment by develop-productivity** [comment]
![image](https://github.com/Junyi42/sd-dino/assets/87483029/d0b42dac-f17d-464d-b132-0bf975edf81f)
This is Code reference abrove in `extractor_sd.py`

**Comment by Junyi42** [comment]
Hi, thank you for your interest in our project. I'd be happy to clarify the code behavior:

The inference code is designed for a `batch_size` of `1` for simplicity, hence `N` is always `1`, and `tensor[0]` is equivalent to `tensor.squeeze(0)`. This doesn't discard any other samples since there is only one sample in the batch.

For PCA implementation, please note that the implementation of the PCA used in our default setting is actually the `co_pca` function in [utils_correspondence.py](https://github.com/Junyi42/sd-dino/blob/master/utils/utils_correspondence.py#L358). The `pca_process` function here is retained for completeness but may not be the one used in our default setting.

Feel free to ask if you have any more questions. Thank you!

**Comment by develop-productivity** [comment]
> Hi, thank you for your interest in our project. I'd be happy to clarify the code behavior:
> 
> The inference code is designed for a `batch_size` of `1` for simplicity, hence `N` is always `1`, and `tensor[0]` is equivalent to `tensor.squeeze(0)`. This doesn't discard any other samples since there is only one sample in the batch.
> 
> For PCA implementation, please note that the implementation of the PCA used in our default setting is actually the `co_pca` function in [utils_correspondence.py](https://github.com/Junyi42/sd-dino/blob/master/utils/utils_correspondence.py#L358). The `pca_process` function here is retained for completeness but may not be the one used in our default setting.
> 
> Feel free to ask if you have any more questions. Thank you!

Thank you for your patient explanation, I will continue to study this work carefully.
