### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'is_tensor'

### ISSUE THREAD

**Issue by murmurelo111** [Junyi42/sd-dino#8]
Hello,I'm sorry to bother you again. I've encountered a version issue. My TensorFlow and Keras versions are 2.13.1, and I'm getting this error. Could you please let me know the Keras version requirements for this code? I couldn't find any helpful answers online, and despite using a global search, I haven't found any occurrences of the "is_tensor" function in the code.
Thanks!

**Comment by murmurelo111** [comment]
It occurs when I ran `pck_spair_pascal.py`
<img width="1085" alt="eb7925d9d3f993726729e6dee5aee98" src="https://github.com/Junyi42/sd-dino/assets/129838471/40bbd349-cbd3-4180-a489-c1f7d3d55bb4">

**Comment by Junyi42** [comment]
Hi @murmurelo111,

Sorry that I haven't met a similar issue. I guess this is caused by some code from `ODISE` repo, and you could refer to [this issue](https://github.com/NVlabs/ODISE/issues/10) to see if it helps. There're also a few similar issues here: https://github.com/arogozhnikov/einops/issues/134, https://github.com/keras-team/tf-keras/issues/189. Hopefully this could be helpful.

Best

**Comment by murmurelo111** [comment]
> Hi @murmurelo111,
> 
> Sorry that I haven't met a similar issue. I guess this is caused by some code from `ODISE` repo, and you could refer to [this issue](https://github.com/NVlabs/ODISE/issues/10) to see if it helps. There're also a few similar issues here: [arogozhnikov/einops#134](https://github.com/arogozhnikov/einops/issues/134), [keras-team/tf-keras#189](https://github.com/keras-team/tf-keras/issues/189). Hopefully this could be helpful.
> 
> Best

Thanks for the reply! This is indeed caused by some code from ODISE repo and I have solved this problem using [this issue](https://github.com/NVlabs/ODISE/issues/10)
